version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "8082:8082"      # Metro web port
      - "19000:19000"    # Expo main port
      - "19001:19001"    # Metro bundler
      - "19002:19002"    # Expo developer tools
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_NO_TELEMETRY=1
      - NODE_ENV=development
      - CI=1
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - WEB_PORT=8082
    command: npm run dev
    stdin_open: true
    tty: true
    network_mode: bridge

networks:
  default:
    driver: bridge
