version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8082:8082"  # Add a new port mapping for Metro
    volumes:
      - .:/app
      - /app/node_modules  # This ensures container's node_modules aren't overwritten
    environment:
      - EXPO_NO_TELEMETRY=1
      - NODE_ENV=development
      - PORT=8082  # Set Metro to use port 8082 instead
    command: sh -c "npm install && npm run dev -- --port 8082"

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
