FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Clean install and generate new package-lock.json
RUN rm -rf node_modules package-lock.json
RUN npm cache clean --force
RUN npm install

# Copy the rest of the code
COPY . .

EXPOSE 19000
EXPOSE 19001
EXPOSE 19002

CMD ["npm", "run", "dev"]
