version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_NO_TELEMETRY=1
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"